function MM_jumpMenu(targ,selObj,restore){ //v3.0
  eval(targ+".location='"+selObj.options[selObj.selectedIndex].value+"'");
  if (restore) selObj.selectedIndex=0;
}
document.write('<select name="select" onChange=MM_jumpMenu("parent",this,0)>')
document.write('<option selected>方正家族网站</option><option>---IT产业---</option>')
document.write('<option value="http://www.founder.com.cn/">方正电子</option>')
document.write('<option value="http://www.foundertech.com/">方正科技</option>')
document.write('<option value="http://www.apabi.com/">方正apabi</option>')
document.write('<option value="http://www.founderegov.com//">方正电子政务</option>')
document.write('<option value="http://www.founderic.com/">深圳方正微电子</option>')
document.write('<option value="http://www.foundersc.com">方正证券网</option>')
document.write('<option value="http://www.founderit.com/">方正世纪</option>')
document.write('<option value="http://www.foundersoft.com">方正国际</option>')
document.write('<option value="http://www.foundersoftware.com">方正软件(苏州)</option>')
document.write('<option value="http://www.foundermedia.com">方正传媒</option>')
document.write('<option value="http://www.foundersec.com/">方正信息安全</option>')
document.write('<option value="http://www.ceie.edu.cn/">中教仪总公司</option>')
document.write('<option value="http://www.foundersz.com/">深圳方正数码</option>')
document.write('<option value="http://www.foundercom.com">方正通信</option>')
document.write('<option value="http://www.founderbn.com/">方正宽带 </option>')
document.write('<option value="http://www.founderorder.com/">方正奥德</option>')
document.write('<option value="http://www.founderie.com/">方正进出口</option>')
document.write('<option value="http://www.cre-ol.com/aboutus/dongan/doninedex2.htm">方正东安稀土</option>')
document.write('<option value="http://www.pfc.edu.cn/">方正软件学院</option>')
document.write('<option value="http://www.founder.com.my">马来西亚方正</option>')
document.write('<option value="http://www.pkucare.com">北大国际医院</option>')
document.write('<option value="http://www.fsspc.com/">西南合成</option>')
document.write('<option value="http://www.ec-founder.com.cn/">方正数码</option>')
document.write('<option value="">方正控股</option>')
document.write('<option>---商业网站---</option>')
document.write('<option value="http://www.auth.com.cn/">方正奥思</option>')
document.write('<option value="http://www.foundertype.com/">方正字库</option>')
document.write('<option value="http://www.eaglerip.com/">方正EagleRip</option>')
document.write('<option value="http://www.sharks.net.cn/">方正SHARKS</option>')
document.write('<option value="http://www.founderdigital.com/">方正数字</option>')
document.write('<option value="http://www.edu-founder.com/">方正测评</option>')
document.write('<option>---公益网站---</option>')
document.write('<option value="http://www.cre-ol.com/">中国稀土在线</option>')
document.write('</select>')