<?php
$height=100;
$width=100;
//新建一个图像；
$im=imagecreatetruecolor($width,$height);
//设置图像中颜色
$red=imagecolorallocate($im,255,0,0);
$green=imagecolorallocate($im,0,255,0);
//背景色
imagefill($im,0,0,$green);
imageline($im,0,$height/2,$width,$height/2,$red);
imagestring($im,5,0,$height/2,'zjmphp',$red);
header('content-type:image/png');
imagepng($im);
//发关到图片
imagejpeg($im,'phpzjm.jpg');
imagedestroy($im);
?>